// File generated by FlutterFire CLI (manually created — run
// `flutterfire configure` to regenerate if firebase project changes).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'reconfigure with FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS — '
          'add GoogleService-Info.plist and reconfigure with FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTE: This google_app_id corresponds to package 'com.arunika'.
  // If the Android applicationId is 'com.example.arunika_app', update
  // android/app/build.gradle.kts (applicationId) to match, or re-register
  // the Firebase app with the correct package name.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEsiIPjzHKhVPipiqWXm-8BVxLDfy6cL4',
    appId: '1:879051861289:android:98781255ab4411b4141b38',
    messagingSenderId: '879051861289',
    projectId: 'arunika-3ffa0',
    storageBucket: 'arunika-3ffa0.firebasestorage.app',
  );
}
